name: month_year_picker
description: The month year picker inspired by the Flutter's date picker design.
version: 0.2.0+3
homepage: https://github.com/zulfahmi93/month-year-picker

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=2.10.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^5.0.0
